accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login
from accounts import views

urlpatterns = [
    url(r'^signup/$', views.signup),
    url(r'^login/$', login),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {
        'next_page': '/accounts/login'
        }),
    url(r'^profile/$', views.profile),
]

kwonil/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^magazine/', include('magazine.urls', namespace='magazine')),
    url(r'^accounts/', include('accounts.urls')),
]

magazine/urls.py
from django.conf.urls import url, include
from magazine import views
from django.conf import settings
from django.conf.urls.static import static

extra_patterns = [
	url(r'^$', views.article_list, name="article_list"),
	url(r'^(?P<pk>\d+)/$', views.article_detail, name='article_detail'),
	url(r'^new/$', views.article_new, name="article_new"),
	url(r'^edit/(?P<pk>\d+)/$', views.article_edit, name="article_edit"),
	url(r'^delete/(?P<pk>\d+)/$', views.article_delete, name="article_delete"),
]


urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^articles/', include(extra_patterns)),
	url(r'^articles/(?P<post_pk>\d+)/comment/new/$', views.comment_new, name='comment_new'),
    url(r'^articles/(?P<post_pk>\d+)/comment/(?P<pk>\d+)/edit$', views.comment_edit, name='comment_edit'),
    url(r'^articles/(?P<post_pk>\d+)/comment/(?P<pk>\d+)/delete$', views.comment_delete, name='comment_delete'),
]

urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

magazine/models.py
from django.db import models
from django import forms
import re

# Create your models here.


def phone_validator(value):
	number = ''.join(re.findall(r'\d+', value))
	if not re.match(r'^01[01678]\d{7,8}$', number):
		raise forms.ValidationError('휴대폰 번호를 입력해주세요')

class PhoneField(models.CharField):
	def __init__(self, *args, **kwargs):
		kwargs.setdefault('max_length', 11)
		super(PhoneField, self).__init__(*args, **kwargs)
		self.validators.append(phone_validator)


class Article(models.Model):
	title = models.CharField(max_length=100)
	content = models.TextField()
	photo = models.ImageField(blank=True)
	phone = PhoneField(max_length=20, blank=True)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.title


class Comment(models.Model):
	article = models.ForeignKey(Article)
	message = models.CharField(max_length=100)

	def __str__(self):
		return self.message

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


class SignupForm(UserCreationForm):
    class Meta:
        fields = UserCreationForm.Meta.field + ('email',)

        def clean_email(self):
            email = self.cleaned_data.get('email', None)
            if email:
                User = get_user_model()
                if User.objects.filter(email=email).exists():
                    raise forms.ValidationError('중복된 이메일입니다')
            return email

magazine/forms.py
from django import forms
from magazine.models import Article, Comment


class ArticleForm(forms.ModelForm):
    is_agree = forms.BooleanField(label='약관동의',
        error_messages={'required': '동의하셔야 이용 가능합니다'})

    class Meta:
        model = Article
        fields = '__all__'


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['message']

accounts/views.py
from django.conf import settings
from django.contrib.auth.views import logout
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm

# Create your views here.


def profile(request):
    return render(request, 'accounts/profile.html')


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('magazine:article_list')
    else:
        form = UserCreationForm
    return render(request, 'accounts/signup.html', {'form': form})


# def logout_view(request):
#     logout(request)
#     return redirect('magazine:article_list')

magazine/views.py
from django.shortcuts import render, redirect, get_object_or_404
from magazine.models import Article, Comment
from magazine.forms import ArticleForm, CommentForm
from django.contrib import messages

# Create your views here.


def index(request):
	return render(request, 'magazine/index.html', {})

def article_list(request):
	article_list = Article.objects.all()
	return render(request, 'magazine/article_list.html', {
			'article_list': article_list
		})

def article_detail(request, pk):
	article = Article.objects.get(pk=pk)
	return render(request, 'magazine/article_detail.html',{
			'article': article
		})

def article_new(request):
	if request.method == 'POST':
		form = ArticleForm(request.POST)
		if form.is_valid():
			article = form.save()
			return redirect('magazine:article_detail', article.pk)
	else:
		form = ArticleForm()
	return render(request, 'magazine/article_new.html', {'form': form})

def article_edit(request, pk):
	form = Article.objects.get(pk=pk)
	if request.method == 'POST':
		form = ArticleForm(request.POST, instance=form)
		if form.is_valid():
			article = form.save()
			return redirect('magazine:article_detail', article.pk)
	else:
		form = ArticleForm(instance=form)
	return render(request, 'magazine/article_new.html', {'form': form})

def article_delete(request, pk):
	form = Article.objects.get(pk=pk)
	form.delete()
	return redirect('magazine:article_list')

def comment_new(request, post_pk):
	if request.method == 'POST':
		form = CommentForm(request.POST)
		if form.is_valid():
			comment = form.save(commit=False)
			comment.article = get_object_or_404(Article, pk=post_pk)
			comment.save()
			messages.success(request, '댓글이 등록되었습니다.')
			return redirect('magazine:article_detail', post_pk)
	else:
		form = CommentForm()
	return render(request, 'magazine/comment_new.html', {'form': form})

def comment_edit(request, post_pk, pk):
	comment = get_object_or_404(Comment, pk=pk)
	if request.method == 'POST':
		form = CommentForm(request.POST, instance=comment)
		if form.is_valid():
			form.save()
			return redirect('magazine:article_detail', post_pk)
	else:
		form = CommentForm(instance=comment)
	return render(request, 'magazine/comment_new.html', {'form': form})

def comment_delete(request, post_pk, pk):
	comment = get_object_or_404(Comment, pk=pk)
	comment.delete()
	return redirect('magazine:article_detail', post_pk)

accounts/templates/accounts/profile.html
{% extends 'magazine/base.html' %}

{% block content %}

{% if user.is_authenticated %}
    {{user}}의 프로필 페이지입니다
{% else %}
    로그인을 해주세요
{% endif %}

{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'magazine/base.html' %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}

    <table>
        {{form.as_table}}
    </table>

    <input type='submit'>
</form>

{% endblock content %}

magazine/templates/magazine/article_delete_confirm.html
<form action="" method="post">
	{% csrf_token %}
	이 포스트를 정말 삭제하시겠습니까?
	<input type='submit'/>
	<a href="{% url 'magazine:article_list' %}">아니오</a>
</form>

magazine/templates/magazine/article_detail.html
{% extends 'magazine/base.html' %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">
                    Welcome to Modern Magazine
                </h1>
            </div>
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4><i class="fa fa-fw fa-check"></i>{{article.title}}</h4>
                    </div>
                    <div class="panel-body">
                        <p>내용 : {{article.content}}</p>
                        <p>번호 : {{article.phone}}</p>

                        {% if article.photo %}
                            <img src="{{article.photo.url}}">
                        {% endif %}

                        <a href="{% url 'magazine:article_list' %}" class='btn btn-default'> 목록으로 </a>
                        <a href="{% url 'magazine:article_edit' article.pk %}" class='btn btn-default'> EDIT </a>
                        <a href="{% url 'magazine:article_delete' article.pk %}" class='btn btn-default'> DELETE </a>
                        <a href="{% url 'magazine:comment_new' article.pk %}" class='btn btn-default'> 댓글 </a>
                    </div>
                    <div class='panel-body'>
                        <h5> 댓글목록 </h5>
                        <ul>
                            {% for comment in article.comment_set.all %}
                                <li>{{comment.message}}
                                <a href="{% url 'magazine:comment_edit' article.pk comment.pk %}"> EDIT </a>
                                <a href="{% url 'magazine:comment_delete' article.pk comment.pk %}"> DEL </a>
                                </li>
                            {% empty %}
                                <li> 등록된 댓글이 없습니다. </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

magazine/templates/magazine/article_list.html
{% extends 'magazine/base.html' %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class='page-header' style='margin-bottom:40px;'>
                    <h1>Welcome to Modern Magazine</h1>
                    <a href="{% url 'magazine:article_new' %}" class='btn btn-primary' style="float:right"> New Article </a>
                </div>
            </div>

            {% for article in article_list %}

            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <a href="{% url 'magazine:article_detail' article.pk %}"><h4><i class="fa fa-fw fa-check"></i>{{article.title}}</h4></a>
                    </div>
                    {% comment %}
                    <div class="panel-body">
                        <p>{{article.content}}</p>
                        <a href="#" class="btn btn-default">Learn More</a>
                    </div>
                    {% endcomment %}
                </div>
            </div>

            {% endfor %}

        </div>
    </div>

{% endblock content %}

magazine/templates/magazine/article_new.html
{% extends 'magazine/base.html' %}

{% block content %}

<form action="" method="post" enctype="multipart/form-data">
{% csrf_token %}
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">
                    Welcome to Modern Magazine
                </h1>
            </div>
            <div class="col-md-4">
                <table>
                {{form.as_table}}
                </table>
                {% comment %}
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4><i class="fa fa-fw fa-check"></i>{{article.title}}</h4>
                    </div>
                    <div class="panel-body">
                        <p>{{article.content}}</p>
                        <a href="#" class="btn btn-default">Learn More</a>
                    </div>
                </div>
                {% endcomment %}
                <div class='panel-body'>
                    <input type='submit'class='btn btn-primary'/>
                    <a href="{% url 'magazine:article_list' %}" class='btn btn-primary'> 목록으로 </a>
                </div>
            </div>
        </div>
    </div>
</form>

{% endblock content %}

magazine/templates/magazine/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Modern Magazine</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static "modern-bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static "modern-bootstrap/css/modern-business.css"%}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static "modern-bootstrap/font-awesome/css/font-awesome.min.css" %}" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'magazine:article_list' %}">Modern Magazine</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="/accounts/profile">{{user}}</a>
                    </li>
                    <li>
                        <a href="{% url 'magazine:article_list' %}">Articles</a>
                    </li>

                    {% if user.is_anonymous %}
                        <li>
                            <a href="/accounts/login">Login</a>
                        </li>
                         <li>
                        <a href="/accounts/signup">Signup</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="/accounts/logout">Logout</a>
                        </li>
                    {% endif %}

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Blog <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="blog-home-1.html">Blog Home 1</a>
                            </li>
                            <li>
                                <a href="blog-home-2.html">Blog Home 2</a>
                            </li>
                            <li>
                                <a href="blog-post.html">Blog Post</a>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Other Pages <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="full-width.html">Full Width Page</a>
                            </li>
                            <li>
                                <a href="sidebar.html">Sidebar Page</a>
                            </li>
                            <li>
                                <a href="faq.html">FAQ</a>
                            </li>
                            <li>
                                <a href="404.html">404</a>
                            </li>
                            <li>
                                <a href="pricing.html">Pricing Table</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

        {% if messages %}
        <div class='messages'>
            {% for message in messages %}
                <div class='alert alert-{{message.tags}}'>
                    {{message}}
                </div>
            {% endfor %}
        {% endif %}


        {% block content %}
        {% endblock %}

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="{% static "modern-bootstrap/js/jquery.js"%}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static "modern-bootstrap/js/bootstrap.min.js"%}"></script>

    <!-- Script to Activate the Carousel -->
    <script>
    $('.carousel').carousel({
        interval: 5000 //changes the speed
    })
    </script>

</body>

</html>

magazine/templates/magazine/comment_new.html
{% extends 'magazine/base.html' %}

{% block content %}

<form action="" method="post">
{% csrf_token %}
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">
                    Welcome to Modern Magazine
                </h1>
            </div>
            <div class="col-md-4">
                <table>
                {{form.as_table}}
                </table>
                {% comment %}
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4><i class="fa fa-fw fa-check"></i>{{article.title}}</h4>
                    </div>
                    <div class="panel-body">
                        <p>{{article.content}}</p>
                        <a href="#" class="btn btn-default">Learn More</a>
                    </div>
                </div>
                {% endcomment %}
                <div class='panel-body'>
                    <input type='submit'class='btn btn-primary'/>
                    <a href="{% url 'magazine:article_list' %}" class='btn btn-primary'> 목록으로 </a>
                </div>
            </div>
        </div>
    </div>
</form>

{% endblock content %}

magazine/templates/magazine/index.html
{% extends 'magazine/base.html' %}

{% block content %}


    <!-- Header Carousel -->
    <header id="myCarousel" class="carousel slide">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
            <div class="item active">
                <div class="fill" style="background-image:url('http://placehold.it/1900x1080&text=Slide One');"></div>
                <div class="carousel-caption">
                    <h2>Caption 1</h2>
                </div>
            </div>
            <div class="item">
                <div class="fill" style="background-image:url('http://placehold.it/1900x1080&text=Slide Two');"></div>
                <div class="carousel-caption">
                    <h2>Caption 2</h2>
                </div>
            </div>
            <div class="item">
                <div class="fill" style="background-image:url('http://placehold.it/1900x1080&text=Slide Three');"></div>
                <div class="carousel-caption">
                    <h2>Caption 3</h2>
                </div>
            </div>
        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="icon-prev"></span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="icon-next"></span>
        </a>
    </header>

    <!-- Page Content -->
    <div class="container">

        <!-- Marketing Icons Section -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">
                    Welcome to Modern Business
                </h1>
            </div>
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4><i class="fa fa-fw fa-check"></i> Bootstrap v3.2.0</h4>
                    </div>
                    <div class="panel-body">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque, optio corporis quae nulla aspernatur in alias at numquam rerum ea excepturi expedita tenetur assumenda voluptatibus eveniet incidunt dicta nostrum quod?</p>
                        <a href="#" class="btn btn-default">Learn More</a>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4><i class="fa fa-fw fa-gift"></i> Free &amp; Open Source</h4>
                    </div>
                    <div class="panel-body">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque, optio corporis quae nulla aspernatur in alias at numquam rerum ea excepturi expedita tenetur assumenda voluptatibus eveniet incidunt dicta nostrum quod?</p>
                        <a href="#" class="btn btn-default">Learn More</a>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4><i class="fa fa-fw fa-compass"></i> Easy to Use</h4>
                    </div>
                    <div class="panel-body">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque, optio corporis quae nulla aspernatur in alias at numquam rerum ea excepturi expedita tenetur assumenda voluptatibus eveniet incidunt dicta nostrum quod?</p>
                        <a href="#" class="btn btn-default">Learn More</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.row -->

        <!-- Portfolio Section -->
        <div class="row">
            <div class="col-lg-12">
                <h2 class="page-header">Portfolio Heading</h2>
            </div>
            <div class="col-md-4 col-sm-6">
                <a href="portfolio-item.html">
                    <img class="img-responsive img-portfolio img-hover" src="http://placehold.it/700x450" alt="">
                </a>
            </div>
            <div class="col-md-4 col-sm-6">
                <a href="portfolio-item.html">
                    <img class="img-responsive img-portfolio img-hover" src="http://placehold.it/700x450" alt="">
                </a>
            </div>
            <div class="col-md-4 col-sm-6">
                <a href="portfolio-item.html">
                    <img class="img-responsive img-portfolio img-hover" src="http://placehold.it/700x450" alt="">
                </a>
            </div>
            <div class="col-md-4 col-sm-6">
                <a href="portfolio-item.html">
                    <img class="img-responsive img-portfolio img-hover" src="http://placehold.it/700x450" alt="">
                </a>
            </div>
            <div class="col-md-4 col-sm-6">
                <a href="portfolio-item.html">
                    <img class="img-responsive img-portfolio img-hover" src="http://placehold.it/700x450" alt="">
                </a>
            </div>
            <div class="col-md-4 col-sm-6">
                <a href="portfolio-item.html">
                    <img class="img-responsive img-portfolio img-hover" src="http://placehold.it/700x450" alt="">
                </a>
            </div>
        </div>
        <!-- /.row -->

        <!-- Features Section -->
        <div class="row">
            <div class="col-lg-12">
                <h2 class="page-header">Modern Business Features</h2>
            </div>
            <div class="col-md-6">
                <p>The Modern Business template by Start Bootstrap includes:</p>
                <ul>
                    <li><strong>Bootstrap v3.2.0</strong>
                    </li>
                    <li>jQuery v1.11.0</li>
                    <li>Font Awesome v4.1.0</li>
                    <li>Working PHP contact form with validation</li>
                    <li>Unstyled page elements for easy customization</li>
                    <li>17 HTML pages</li>
                </ul>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis, omnis doloremque non cum id reprehenderit, quisquam totam aspernatur tempora minima unde aliquid ea culpa sunt. Reiciendis quia dolorum ducimus unde.</p>
            </div>
            <div class="col-md-6">
                <img class="img-responsive" src="http://placehold.it/700x450" alt="">
            </div>
        </div>
        <!-- /.row -->

        <hr>

        <!-- Call to Action Section -->
        <div class="well">
            <div class="row">
                <div class="col-md-8">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, expedita, saepe, vero rerum deleniti beatae veniam harum neque nemo praesentium cum alias asperiores commodi.</p>
                </div>
                <div class="col-md-4">
                    <a class="btn btn-lg btn-default btn-block" href="#">Call to Action</a>
                </div>
            </div>
        </div>

{% endblock content %}